# Generated by Django 5.2.5 on 2025-11-18 08:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0004_view_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="View_Profile",
            new_name="ViewProfile",
        ),
    ]
